#!/usr/bin/env python3
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
"""
Stream Density — all logic for multiplying scenes, cameras, and pipelines.

Importable functions:
    expand_scene_configs()  — expand 1 scene × N density into N scene configs
    generate_pipelines()    — generate DLStreamer pipeline config with N pipelines
    generate_cameras_compose() — generate docker-compose.cameras.yaml with N ffmpeg services
    clone_scene_zip()       — clone a SceneScape scene .zip N times

CLI subcommands:
    python3 stream_density.py clone-zip <base_zip> <output_dir> <scene_name> <camera_name> <density>
    python3 stream_density.py generate  <template_json> <pipeline_out> <cameras_compose_out> <camera_name> <video_file> <density>
"""

import json
import os
import shutil
import sys
import tempfile
import zipfile


# ---------------------------------------------------------------------------
# Scene config expansion (used by swlp-service config.py)
# ---------------------------------------------------------------------------

def expand_scene_configs(base_scene: dict, density: int) -> list:
    """Expand a single scene config into N scene configs with unique names/cameras.

    Args:
        base_scene: dict with keys: scene_name, scene_zip, cameras, video_file, zones
        density: number of copies (1 = no expansion)

    Returns:
        List of N scene config dicts.
    """
    if density <= 1:
        return [base_scene]

    configs = []
    cameras = base_scene.get("cameras", [])
    base_cam = cameras[0] if cameras else ""
    scene_name = base_scene.get("scene_name", "")
    scene_zip = base_scene.get("scene_zip", "")

    for i in range(1, density + 1):
        cam = f"{base_cam}-{i}" if base_cam else ""
        stem, ext = os.path.splitext(scene_zip) if scene_zip else ("", "")
        configs.append({
            "scene_name": f"{scene_name} {i}",
            "scene_zip": f"{stem}-{i}{ext}" if scene_zip else "",
            "cameras": [cam] if cam else [],
            "video_file": base_scene.get("video_file", ""),
            "zones": dict(base_scene.get("zones", {})),
        })
    return configs


# ---------------------------------------------------------------------------
# DLStreamer pipeline config generation (used by init.sh)
# ---------------------------------------------------------------------------

def generate_pipelines(template_path: str, output_path: str,
                       camera_name: str, density: int) -> None:
    """Generate DLStreamer pipeline config with N pipelines (one per camera).

    Args:
        template_path: path to pipeline-config.json template (uses {{CAMERA_NAME}})
        output_path: where to write the generated config
        camera_name: base camera name
        density: number of camera copies
    """
    with open(template_path) as f:
        tpl = json.load(f)

    base_pipeline = tpl["config"]["pipelines"][0]
    base_str = json.dumps(base_pipeline)

    pipelines = []
    for i in range(1, density + 1):
        cam = f"{camera_name}-{i}" if density > 1 else camera_name
        pipelines.append(json.loads(base_str.replace("{{CAMERA_NAME}}", cam)))

    tpl["config"]["pipelines"] = pipelines
    with open(output_path, "w") as f:
        json.dump(tpl, f, indent=2)


# ---------------------------------------------------------------------------
# docker-compose.cameras.yaml generation (used by init.sh)
# ---------------------------------------------------------------------------

def generate_cameras_compose(output_path: str, camera_name: str,
                             video_file: str, density: int) -> None:
    """Generate docker-compose.cameras.yaml with N ffmpeg services.

    Args:
        output_path: where to write the compose file
        camera_name: base camera name
        video_file: video filename in sample_data/
        density: number of camera copies
    """
    import yaml

    services = {}
    for i in range(1, density + 1):
        cam = f"{camera_name}-{i}" if density > 1 else camera_name
        svc_name = f"lp-cams-{i}" if density > 1 else "lp-cams"
        services[svc_name] = {
            "image": "linuxserver/ffmpeg:version-8.0-cli",
            "command": (
                f"-nostdin -re -stream_loop -1 -i /workspace/media/{video_file} "
                f"-c:v copy -an -f rtsp -rtsp_transport tcp rtsp://mediaserver:8554/{cam}"
            ),
            "volumes": ["vol-sample-data:/workspace/media"],
            "networks": ["storewide-lp"],
            "depends_on": ["mediaserver"],
            "restart": "always",
            "pids_limit": 1000,
        }

    with open(output_path, "w") as f:
        f.write("# Auto-generated by stream_density.py — do not edit\n")
        yaml.dump({"services": services}, f, default_flow_style=False, sort_keys=False)


# ---------------------------------------------------------------------------
# Scene zip cloning (used by scene-import.sh inside container)
# ---------------------------------------------------------------------------

def clone_scene_zip(base_zip: str, output_dir: str, scene_name: str,
                    camera_name: str, index: int) -> str:
    """Clone a scene zip with a unique scene name and camera ID.

    Returns the filename of the new zip.
    """
    new_scene_name = f"{scene_name} {index}"
    new_camera = f"{camera_name}-{index}"
    base_stem = os.path.splitext(os.path.basename(base_zip))[0]
    new_zip_name = f"{base_stem}-{index}.zip"
    new_zip_path = os.path.join(output_dir, new_zip_name)

    with tempfile.TemporaryDirectory() as tmpdir:
        with zipfile.ZipFile(base_zip, "r") as zf:
            for member in zf.namelist():
                filename = os.path.basename(member)
                if not filename:
                    continue
                with zf.open(member) as src, open(os.path.join(tmpdir, filename), "wb") as dst:
                    dst.write(src.read())

        files = os.listdir(tmpdir)
        json_files = [f for f in files if f.lower().endswith(".json")]
        resource_files = [f for f in files if not f.lower().endswith(".json")]

        if not json_files:
            print(f"ERROR: No JSON file in {base_zip}", file=sys.stderr)
            sys.exit(1)

        json_path = os.path.join(tmpdir, json_files[0])
        with open(json_path, "r") as f:
            data = json.load(f)

        data["name"] = new_scene_name
        for cam in data.get("cameras", []):
            cam["uid"] = new_camera
            cam["name"] = new_camera

        new_json_name = f"{new_scene_name}.json"
        new_json_path = os.path.join(tmpdir, new_json_name)
        with open(new_json_path, "w") as f:
            json.dump(data, f, indent=2)
        if json_path != new_json_path:
            os.remove(json_path)

        renamed_resources = []
        for rf in resource_files:
            ext = os.path.splitext(rf)[1]
            new_rf_name = f"{new_scene_name}{ext}"
            new_rf_path = os.path.join(tmpdir, new_rf_name)
            old_rf_path = os.path.join(tmpdir, rf)
            if old_rf_path != new_rf_path:
                shutil.move(old_rf_path, new_rf_path)
            renamed_resources.append(new_rf_name)

        with zipfile.ZipFile(new_zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            zf.write(new_json_path, new_json_name)
            for rf_name in renamed_resources:
                zf.write(os.path.join(tmpdir, rf_name), rf_name)

    return new_zip_name


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _cli_clone_zip(args):
    if len(args) != 5:
        print("Usage: stream_density.py clone-zip <base_zip> <output_dir> <scene_name> <camera_name> <density>",
              file=sys.stderr)
        sys.exit(1)
    base_zip, output_dir, scene_name, camera_name = args[:4]
    density = int(args[4])
    if density < 1:
        print("ERROR: density must be >= 1", file=sys.stderr)
        sys.exit(1)
    os.makedirs(output_dir, exist_ok=True)
    names = []
    for i in range(1, density + 1):
        names.append(clone_scene_zip(base_zip, output_dir, scene_name, camera_name, i))
    print(",".join(names))


def _cli_generate(args):
    if len(args) != 6:
        print("Usage: stream_density.py generate <template> <pipeline_out> <cameras_out> <camera_name> <video_file> <density>",
              file=sys.stderr)
        sys.exit(1)
    template, pipeline_out, cameras_out, camera_name, video_file = args[:5]
    density = int(args[5])
    generate_pipelines(template, pipeline_out, camera_name, density)
    generate_cameras_compose(cameras_out, camera_name, video_file, density)
    print(f"Generated {density} pipeline(s) → {pipeline_out}", file=sys.stderr)
    print(f"Generated {density} camera service(s) → {cameras_out}", file=sys.stderr)


def main():
    if len(sys.argv) < 2:
        print("Usage: stream_density.py <command> [args...]", file=sys.stderr)
        print("Commands:", file=sys.stderr)
        print("  clone-zip  <base_zip> <output_dir> <scene_name> <camera_name> <density>", file=sys.stderr)
        print("  generate   <template> <pipeline_out> <cameras_out> <camera_name> <video_file> <density>", file=sys.stderr)
        sys.exit(1)

    cmd = sys.argv[1]
    if cmd == "clone-zip":
        _cli_clone_zip(sys.argv[2:])
    elif cmd == "generate":
        _cli_generate(sys.argv[2:])
    else:
        print(f"Unknown command: {cmd}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
